"""Configuration management and settings."""

from music_workflow.config.settings import (
    WorkflowSettings,
    DownloadConfig,
    ProcessingConfig,
    DeduplicationConfig,
    NotionConfig,
    EagleConfig,
    SpotifyConfig,
    FeatureFlags,
    Settings,
    get_settings,
    reset_settings,
)
from music_workflow.config.constants import (
    VERSION,
    SUPPORTED_AUDIO_FORMATS,
    LOSSLESS_FORMATS,
    LOSSY_FORMATS,
    DEFAULT_OUTPUT_FORMATS,
    DEFAULT_TARGET_LUFS,
    KEY_NOTATION,
    SPOTIFY_KEY_MAP,
    SPOTIFY_MODE_MAP,
    Platform,
    ProcessStatus,
    NotionProperties,
    DefaultPaths,
    Timeouts,
    RetryConfig,
    DedupThresholds,
)

__all__ = [
    # Settings
    "WorkflowSettings",
    "Settings",
    "DownloadConfig",
    "ProcessingConfig",
    "DeduplicationConfig",
    "NotionConfig",
    "EagleConfig",
    "SpotifyConfig",
    "FeatureFlags",
    "get_settings",
    "reset_settings",
    # Constants
    "VERSION",
    "SUPPORTED_AUDIO_FORMATS",
    "LOSSLESS_FORMATS",
    "LOSSY_FORMATS",
    "DEFAULT_OUTPUT_FORMATS",
    "DEFAULT_TARGET_LUFS",
    "KEY_NOTATION",
    "SPOTIFY_KEY_MAP",
    "SPOTIFY_MODE_MAP",
    "Platform",
    "ProcessStatus",
    "NotionProperties",
    "DefaultPaths",
    "Timeouts",
    "RetryConfig",
    "DedupThresholds",
]
